import { z } from "zod";

export const academicReportSchema = z.object({
  reportType: z.string().min(1, "Report type is required"),
  className: z.string().min(1, "Class is required"),
  subject: z.string().min(1, "Subject is required"),
  academicYear: z.string().min(1, "Academic year is required"),
  term: z.string().min(1, "Term is required"),
  generatedBy: z.string().min(1, "Generated by is required"),
  date: z.string().min(1, "Date is required"),
  status: z.string().min(1, "Status is required"),
});

export type AcademicReportFormData = z.infer<typeof academicReportSchema>;
